import Head from 'next/head'
import Protected from '../auth/Protected'
import dbConnect from '../config/dbConnect'

dbConnect()

export default function Home() {
  return (
    <div>
      <Head>
        <title>Albi Portfolio </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Protected>
          <p className='text-red-500 bg-slate-600 w-full text-center '>
            Albi is ready to go with Tailwind !!
          </p>
        </Protected>
      </main>
    </div>
  )
}
